<?php
$title = "Termos de Uso";
?>
<article class="quemSomos">
    <section class="container">
        <div class="containerText">
            <h1>Termos De Uso</h1>
            <p>
            Por este TERMO DE USO, o USUÁRIO do SEBOOK fica ciente e concorda que ao utilizar o sistema do SEBOOK, automaticamente aderirá e concordará em se submeter integralmente às condições do presente TERMO DE USO e qualquer de suas alterações futuras.
            O Usuário concorda que a sua identificação é personalíssima, não podendo ser transferida em qualquer hipótese.<br>
            Ao utilizar ou se cadastrar no Sebook, o Usuário manifesta expressamente que leu completamente, entendeu e concordou com as regras, termos e condições estabelecidos nestes Termos de Uso.<br>  
            Ressalta-se que o Sebook poderá, a qualquer momento, sem notificação prévia, alterar qualquer disponibilização de serviços oferecidos ou eventuais configurações.<br>
            USUÁRIO(S): se dividirão em : LEITOR(ES) e SEBO(S).<br>
            LEITOR(ES): são as pessoas físicas que acessam e usam os serviços providos pelo SEBOOK, essencialmente buscam livros a serem adquiridos nos SEBO(S) PARCEIRO(S) existentes em sua região.<br>
            SEBO(S) PARCEIRO(S): são as pessoas jurídicas que possuem os livros usados a serem vendidos através da divulgação de seu acervo, anúncios ou publicidade no SEBOOK.<br>
            SITE: conjunto de páginas ou lugar no ambiente da Internet ocupado com CONTEÚDO de um sebo.<br>
            SITE SEBOOK: é o SITE de internet registrado no Núcleo de Informação e Coordenação do Ponto BR (www.registro.br) sob o domínio sebook.com.br, com todos os recursos e ferramentas relacionadas a este, bem como outros SITES e domínios da marca SEBOOK registrados nos respectivos órgãos responsáveis pela classificação e registro do domínio.<br>
            COOKIE(S): pequeno arquivo de texto armazenado nos navegadores. Este recurso possibilita a identificação de USUÁRIOS e o direcionamento de documentos de acordo com parâmetros pré-estabelecidos.<br>
            LINK(S): significa um acesso eletrônico, seja por meio de imagens ou palavras, que permite a conexão a outras telas de um mesmo SITE, ou, ainda, de outros SITES.<br>
            SPAM: são e-mails enviados a um grupo de USUÁRIOS sem a sua devida permissão.<br>
            CONTEÚDO: inclui texto, programas, scripts, gráficos, fotos, sons, imagens, músicas, vídeos, combinações audiovisuais, animações, recursos interativos e outros materiais que o(s) LEITOR(ES), têm acesso ou submetem a um SITE.<br>
            Este documento informa as responsabilidades, deveres e obrigações que todo(s) o(s) USUÁRIO(S) assume(m) ao acessar e/ou utilizar o site SEBOOK e seus serviços relacionados como softwares, complementos, plug-ins, barras e acessórios a não ser quando regido por um TERMO DE USO específico.<br>
             As funcionalidades adicionais do SEBOOK, possíveis graças à tecnologia eletrônica, não desvirtuam o fato de o site SEBOOK adicionar em seu meio eletrônico informações de ANUNCIANTES pelas quais o site SEBOOK, NÃO se responsabiliza (assim como anúncios classificados em jornais, rádio ou televisão).<br>
            Desse modo, o(s) USUÁRIO(S) deve(m) checar a veracidade das informações obtidas pelo meio eletrônico do site SEBOOK e tomar todas as medidas necessárias para se proteger de danos, fraudes ou estelionatos, inclusive "on-line" e "off-line".<br>
            O USUÁRIO(S) deve(m) ler com atenção os termos abaixo antes de acessar ou usar o site SEBOOK, pois, o acesso ou uso deste implica em concordância integral com tais termos universais.<br>
            O site SEBOOK e os demais participantes do site somente fornecerão ao USUÁRIO(S) informações e serviços mediante expressa concordância aos TERMOS DE USO, condições e informações aqui contidas, assim como aos demais documentos incorporados ao mesmo por referência. O uso do site SEBOOK significa a total concordância com tais termos, condições e informações.<br>
            O SEBOOK captura e divulga anúncios/eventos advindos de diversos SEBO(S), logo, não atua como prestador de serviços de consultoria ou ainda intermediário ou participante em nenhum negócio jurídico entre o LEITOR(ES) e o(s) SEBO(S).<br>
            Assim, o site SEBOOK não assume qualquer responsabilidade que advenha das relações existentes entre o LEITOR(ES) e o(s) SEBO(S), sejam elas diretas ou indiretas, e/ou também;<br>
            <b>A.</b> Pelo CONTEÚDO e funcionamento dos SITES das lojas "on-line" SEBO(S);<br>
            <b>B.</b> Por negociações efetuadas entre LEITOR(ES) e SEBO(S);<br>
            <b>C.</b> Pela entrega de produtos e serviços SEBO(S), sendo tais negociações por conta e risco do LEITOR(ES), que deve cercar-se de todos os cuidados necessários;<br>
            <b>D.</b> Por danos e/ou prejuízos resultantes das negociações entre USUÁRIO e SEBO(S) cadastrados no SITE SEBOOK;<br>
            <b>E.</b> Pela origem, qualidade e quantidade dos produtos e serviços do SEBO(S) cadastrados no SITE SEBOOK, sendo delas total e exclusiva responsabilidade;<br>
            <b>F.</b> Por transações efetuadas "on-line" na Internet, que são de inteira e exclusiva responsabilidade de quem disponibilizar os respectivos produtos ou serviços.<br>
            Portanto, o site SEBOOK não é responsável por qualquer ação ou omissão do USUÁRIO(S) baseadas nas informações, anúncios, vídeos, fotos ou outros materiais veiculados pelo SEBOOK. Adicionalmente, o site SEBOOK envidará seus melhores esforços para manter o SITE sempre atualizado, completo e preciso, mas não se responsabilizará por erro, fraude, inexatidão, imprecisão ou divergência nos dados, vídeos, fotos ou outros materiais relacionados a anúncios ou à inexatidão das informações contidas e apresentadas no SITE SEBOOK.<br>
            Eventuais erros no funcionamento do site SEBOOK serão corrigidos durante o período que for necessário para manutenção. O site SEBOOK não se responsabiliza por danos decorrentes da não disponibilidade ou erro de funcionamento do SITE SEBOOK.<br>
            O SITE SEBOOK, seus funcionários, agentes, colaboradores, representantes e procuradores, devem ser eximidos de toda e qualquer responsabilidade decorrente de qualquer tipo de reclamação ou ação legal contra um ou mais SEBO(S), sejam elas promovidas por um ou mais LEITOR(ES), ou inclusive por algum terceiro.<br>
            Também não serão de responsabilidade do site SEBOOK as obrigações tributária que recaiam nas atividades entre LEITOR(ES) e SEBO(S) no SITE SEBOOK. Assim, ao adquirir algum bem ou serviço, o LEITOR(ES) consumidor deverá exigir documento fiscal do SEBO(S), a menos que este esteja legalmente dispensado de fornecê-la.<br>
            Toda transação realizada pela Internet deve ocorrer com toda cautela e bom senso redobrados. Logo, o LEITOR(ES) deverá avaliar os riscos das negociações, levando em consideração que pode, eventualmente, lidar com pessoas valendo-se de falsas identidades ou ainda com menores de idade.<br>
            O SEBOOK sugere ao LEITOR(ES) que:<br>
            <b>A.</b> Verifique com toda cautela a documentação e/ou características de qualquer dos produtos e/ou serviços ofertados antes da conclusão de qualquer negócio, concordando que ao negociar com o(s) SEBO(S) dos produtos e/ou serviços ofertados o fará por sua única conta e risco;<br>
            <b>B.</b> Seja cuidadoso com os dados de sua identificação individual sempre que acessar a Internet, informando-os apenas em operações em que existam proteção de dados;<br>
            <b>C.</b> Tome quaisquer outras medidas necessárias para se proteger de danos, inclusive fraudes ou estelionato "on-line";<br>
            <b>D.</b> Cumpra rigorosamente todas as determinações deste TERMO DE USO.<br>
             O LEITOR(ES) através deste TERMO DE USO aceita ser identificado pelo sistema do SITE SEBOOK, como, por exemplo, no uso de COOKIES e/ou de outras tecnologias. Tal política visa à melhoria contínua dos serviços prestados pelo SITE SEBOOK.<br>
            Caso exista alguma dúvida referente aos dados coletados pelo site SEBOOK consulte a nossa Política de Privacidade disponível em <a href="<?= _URLBASE_ ?>area/user/pages/politicaDePrivacidade" class="Seguranca"><b>https://www.sebook.com.br/politicaDePrivacidade</b></a><br>
            Caso o LEITOR(ES) acesse o SITE de parceiros, patrocinadores, SEBO(S) e demais SITES ou serviços que sejam acessados através do SITE SEBOOK, é possível que haja solicitação de informações financeiras e/ou pessoais do consumidor LEITOR(ES). Tais informações não serão enviadas pelo LEITOR(ES) ao SITE SEBOOK, e sim diretamente ao solicitante, não tendo o SITE SEBOOK, portanto, qualquer responsabilidade pela utilização e manejo dessa informação.<br>
            O site SEBOOK envidará seus melhores esforços para evitar o envio não solicitado de e-mails. Para tanto, resta estabelecido que seja absolutamente proibida à utilização do site SEBOOK para a distribuição de SPAM ou o envio indiscriminado de mensagens de qualquer natureza via correio eletrônico.<br>
            Fica a critério exclusivo do site SEBOOK suspender e/ou inabilitar definitivamente e aplicar as medidas jurídicas cabíveis aos LEITOR(ES) que se utilizarem do site SEBOOK com a finalidade de promover seus produtos ou serviços à venda ou com qualquer outro fim, e que forem denunciados pelas pessoas que receberam essas mensagens SPAM.<br>
            Para a obtenção de informações sobre um anúncio, o LEITOR(ES) do site SEBOOK não terá que desembolsar qualquer taxa para o(s) SEBO(S), a que título seja. Qualquer infração nesse sentido por parte do SEBO(S) deve ser imediatamente notificada ao site SEBOOK.<br>
            Os materiais do site SEBOOK poderão ser acessados, utilizados e impressos para o uso pessoal e não comercial do LEITOR(ES), logo, o LEITOR(ES) não poderá copiar, modificar, criar trabalho derivado, transferir ou vender qualquer informação, "software", lista de LEITOR(ES) e outras listas, produtos ou serviços obtidos no site SEBOOK para uso comercial.<br>
            Além disso, o LEITOR(ES) não poderá:<br>
            <b>A.</b> Transmitir ou enviar informações de qualquer natureza que possam incitar induzir, ou promover atitudes discriminatórias, mensagens violentas ou delituosas que atentem contra aos bons costumes, à moral ou ainda que contrariem a ordem pública;<br>
            <b>B.</b> Cadastrar-se com informações de propriedade de terceiros ou falsas;<br>
            <b>C.</b> Utilizar os produtos e/ou serviços disponíveis no site SEBOOK para fins diversos daqueles a que se destinam;<br>
            <b>D.</b> Alterar, apagar e/ou corromper dados e informações de terceiros;<br>
            <b>E.</b> Violar a privacidade de quaisquer LEITOR(ES) e/ou SEBO(S);<br>
            <b>F.</b> Violar propriedade intelectual do SITE SEBOOK, de terceiros em geral, ou seja, direito autoral, marca, patente, etc., através de reprodução de material, sem a prévia autorização do proprietário;<br>
            <b>G.</b> Usar "nome de USUÁRIO" que guarde semelhança com o nome "SEBOOK";<br>
            <b>H.</b> Transmitir ou enviar arquivos com vírus de computador, com CONTEÚDO invasivo, destrutivo ou que cause dano temporário ou permanente nos equipamentos do destinatário e/ou do SITE SEBOOK;<br>
            <b>I.</b> Utilizar nomes e/ou apelidos considerados ofensivos, bem como os que contenham dados pessoais de qualquer LEITOR(ES) e/ou SEBO(S).<br>
            <b>J.</b> Transmitir ou enviar informações de propriedade de terceiros;<br>
            <b>K.</b> Usar endereços de computadores, de rede ou de correio eletrônico falso;<br>
            <b>L.</b> Utilizar qualquer nome e/ou apelido que insinue ou sugira que os produtos ou serviços anunciados pertencem ao site SEBOOK ou que fazem parte de promoções suas;<br>
            <b>M.</b> Utilizar materiais que contenham qualquer vírus, worms, malware e outros programas de computador que possa causar danos ao site ou ao LEITOR(ES) ou SEBO(S) do SITE SEBOOK;<br>
            <b>N.</b> Realizar a divulgação de materiais ilegais, agressivos, caluniosos, abusivos, difamatórios, discriminatórios, ameaçadores, danosos, invasivos da privacidade de terceiros, terroristas, vulgares, obscenos ou ainda condenáveis de qualquer tipo ou natureza que sejam prejudiciais a menores e à preservação do meio ambiente de algum modo.<br>
            <b>O.</b> Anexar URLs, endereços de e-mail ou outro material publicitário ou de cunho de anúncio e/ou publicidade de terceiros sem prévia autorização do SITE SEBOOK.<br>
            O descumprimento às condições, termos e observações deste TERMO DE USO dá ao site SEBOOK o direito de cancelar, suspender, excluir e/ou desativar o cadastro ou o material enviado pelo LEITOR(ES), temporária ou definitivamente, ao seu único e exclusivo critério, sem prejuízo das cominações legais pertinentes e sem a necessidade de comunicar ao LEITOR(ES) a ação tomada dentro do seu sistema.<br>
            Todos os materiais do SITE SEBOOK, incluindo, mas não se limitando a apresentação, "layout", marcas, logotipos, sistemas, produtos, denominações de serviços e quaisquer outros materiais, inclusive bases de dados, programas, arquivos, imagens, vídeos ou materiais de qualquer outra natureza e que tenham contratualmente autorizadas suas veiculações no site SEBOOK são protegidas pela legislação de Propriedade Intelectual.<br>
            São de titularidade do site SEBOOK e de suas afiliadas, clientes ou fornecedores os direitos de uso e propriedade delimitando que sua reprodução, transmissão e distribuição de tais materiais, não são permitidas sem o expresso consentimento por escrito do site SEBOOK ou do respectivo titular, sobretudo para o fim econômico ou comercial.<br>
            Caracterizará como infração da legislação vigente, o uso indevido de materiais protegidos por propriedade intelectual (direito autoral, marcas comerciais, patentes etc.) apresentados no site SEBOOK, sujeitando-se o LEITOR(ES) infrator às medidas judiciais cabíveis à espécie, sem prejuízo de eventual indenização por perdas e danos e honorários advocatícios ao SITE SEBOOK, bem como a terceiros que venham a sofrer pelo ato do LEITOR(ES).<br>
            Os riscos derivados da utilização do site SEBOOK são do USUÁRIO(S), logo, se seu uso resultar na necessidade de serviços e/ou reposição de material, equipamento, propriedade ou informação do USUÁRIO(S) o site SEBOOK e suas afiliadas não serão responsáveis por tais custos.<br>
            Os produtos, informações, valores, serviços sistemas e/ou "software", publicados no site SEBOOK podem conter imprecisões e/ou erros de grafia, razão pela qual o SEBOOK envidará seus melhores esforços para manter o SITE atualizado periodicamente.<br>
            De nenhum modo o SEBOOK será responsabilizado por qualquer dano direto, indireto, especial, incidental ou de qualquer fato resultante do uso do SEBOOK, inclusive por quaisquer informações, produtos e/ou serviços obtidos através dele ou em decorrência do seu uso.<br>
            O SEBOOK contém LINKS para outros SITES operados por terceiros que não o SEBOOK e/ou suas afiliadas. Esses LINKS são fornecidos somente para sua referência, razão pela qual, o SEBOOK não tem controle sobre esses outros SITES e não se responsabiliza pelo CONTEÚDO dos mesmos, sendo que a inclusão desses LINKS no SEBOOK não implica na aprovação do material ou qualquer associação com seus proprietários. Assim, ao acessar e usar esses SITES, suas informações, materiais, produtos e/ou serviços, o USUÁRIO(S) estará fazendo por sua conta e risco.<br>
            O mesmo se aplica aos SITES que possuam LINKS para o SEBOOK, eis que o SEBOOK não possui controle sobre os mesmos.<br>
            A Política de Privacidade do SEBOOK é aplicável ao USUÁRIO(S), quando este acessar o 
            site SEBOOK e pode ser encontrada no seguinte LINK: <a href="<?= _URLBASE_ ?>area/user/pages/politicaDePrivacidade" class="Seguranca"><b>politica de privacidade.</b></a><br> 
            Desse modo, ao ser encaminhado para outro site, o LEITOR(ES) estará sujeito às políticas deste site, sobre o qual o SEBOOK não tem qualquer relação.<br>
            O SEBOOK, suas afiliadas e seus fornecedores poderão fazer mudanças nos serviços, produtos, informações e quaisquer outros materiais do SEBOOK, inclusive encerrar suas atividades a qualquer momento sem a necessidade de enviar qualquer notificação prévia ao LEITOR(ES) e sem o direito de indenização a qualquer LEITOR(ES) ou SEBO(S).<br>
            O SEBOOK poderá alterar, modificar e/ou ajustar este TERMO DE USO a qualquer tempo, sendo que essas alterações, modificações e/ou ajustes terão efeito somente após se tornarem públicos. Desse modo, o LEITOR(ES) obriga-se a rever o TERMO DE USO do SEBOOK de tempos em tempos, restando claro que o USUÁRIO(S) subordina-se à aceitação do TERMO DE USO vigente no momento de seu acesso ou faz uso dos serviços prestados pelo SEBOOK.<br>
            O LEITOR(ES) e/ou SEBO(S) indenizará o SEBOOK, suas filiais, empresas controladas, controladoras, colaboradores, representantes, administradores e empregados por qualquer ação promovida por outros LEITOR(ES), SEBO(S) ou terceiros decorrentes de atividades ilegais no SEBOOK em razão do descumprimento do TERMO DE USO e/ou demais políticas do SEBOOK; ou ainda pela violação de qualquer lei, direito de terceiros, responsabilizando-se por eventuais perdas e danos, além de honorários advocatícios.<br>
            O LEITOR(ES) e o(s) SEBO(S) detêm de todos os direitos de propriedade sobre a informação, texto, gráfico ou outros materiais que publicar no SEBOOK, no entanto, o SITE pode reproduzir publicar e distribuir todos os arquivos, textos, gráficos integral ou em partes do seu CONTEÚDO "on-line" e "off-line".<br>
            O LEITOR(ES) e o(s) SEBO(S) podem editar ou remover o CONTEÚDO do SEBOOK a qualquer momento, todavia, se o SEBOOK tiver realizado a distribuição do CONTEÚDO do LEITOR(ES) e o(s) SEBO(S) para outros, não se compromete a fazer a alteração do que tiver distribuído.<br>
            Este TERMO DE USO se aplica a todos os SEBO(S) do SEBOOK, inclusive os LEITOR(ES) que também contribuem com CONTEÚDO do SEBOOK.<br>
            Ao contribuir/submeter qualquer CONTEÚDO no SITE SEBOOK, o(s) LEITOR(ES) e o(s) SEBO(S), garantem que possuem as licenças necessárias, direitos, autorizações e permissões para publicar o CONTEÚDO enviado ao SEBOOK. O LEITOR(ES)) e SEBO(S) concedem ao SEBOOK uma licença mundial, perpétua, irrevogável, livre de royalties, transferível, bem como e inclusive o direito de licença para usar, copiar, modificar, apagar na sua totalidade, adaptar, publicar, traduzir, criar trabalhos derivados, vender, distribuir materiais e/ou incorporar esses materiais em qualquer formato, meio ou tecnologia sem qualquer prejuízo ao LEITOR(ES) e o(s) SEBO(S).<br>
            Desta forma, nenhum dos materiais deve ser sujeito/submetido a qualquer obrigação de confiança por parte do SEBOOK, seus funcionários, agentes, colaboradores e representantes sem os direitos ou licenças disponíveis para isso.<br>
            O site SEBOOK reserva-se ao direito de alterar, condensar ou excluir qualquer CONTEÚDO do site SEBOOK que considere, a seu exclusivo critério, violar as diretrizes de CONTEÚDO, a legislação brasileira ou de qualquer outra disposição do presente TERMO DE USO.<br>
            O LEITOR(ES) pode enviar vídeos e comentários, todavia, o SEBOOK não garante a confidencialidade em relação a qualquer CONTEÚDO enviado, sendo importante mencionar que o LEITOR(ES) é o único responsável por seu CONTEÚDO e pelas conseqüências de enviá-lo ou publicá-lo, garantindo que possui ou tem as licenças necessárias, direitos, autorizações e permissões para publicá-lo.<br>
            O USUÁRIO(S) autoriza o SEBOOK a usar todas as patentes, marcas registradas, segredos de negócio, direitos autorais ou outros direitos de propriedade e tais CONTEÚDOS para a publicação de acordo com este TERMO DE USO. Assim, cumpre esclarecer que o USUÁRIO(S) mantém todos os direitos de propriedade sobre seu CONTEÚDO, entretanto, ao enviar o CONTEÚDO ao SEBOOK, o USUÁRIO(S) pelo presente, cede ao SEBOOK licença mundial, não exclusiva, isenta de royalties, passível de ser sublicenciada e transferida, para usar, reproduzir, distribuir, preparar trabalhos derivados, exibir e executar o CONTEÚDO em conexão com o SEBOOK (e de seus sucessores e afiliados), inclusive, mas sem se limitar a atividades de promoção e redistribuição parcial ou total do Serviço (e trabalhos derivados) em qualquer formato de mídia e através de qualquer canal de mídia.<br>
            O USUÁRIO(S) também cede a todos os USUÁRIO(S) do SEBOOK uma licença não-exclusiva para acessar o seu CONTEÚDO por meio do SEBOOK (e de seus sucessores e afiliados), e para usar, reproduzir, distribuir, exibir e executar tal CONTEÚDO conforme permitido pela funcionalidade do site SEBOOK e de acordo com o TERMO DE USO. As licenças acima cedidas pelo USUÁRIO(S) para o site SEBOOK, irão encerrar dentro de um tempo comercialmente razoável após a remoção ou exclusão pelo USUÁRIO(S). As licenças acima, cedidas pelo USUÁRIO(S) em relação aos comentários são permanentes e irrevogáveis.<br>
            O USUÁRIO(S) afirma que não enviará material protegido por direitos autorais, por segredo de negócio ou de qualquer outra forma protegido por direitos de terceiros, a menos que tenha permissão do legítimo proprietário do material ou caso esteja legalmente autorizado a publicar o material e ceder ao site do SEBOOK todos os direitos de licença aqui concedidos.<br>
            O SEBOOK não endossa qualquer CONTEÚDO enviado por qualquer USUÁRIO(S) ou licenciante ou qualquer opinião, recomendação ou conselho ali expresso. O SEBOOK renuncia expressamente toda e qualquer responsabilidade ligada ao CONTEÚDO.<br>
            O SEBOOK não permite atividades que violem os direitos autorais, nem os direitos de propriedade intelectual em seu site, assim, o SITE do SEBOOK removerá todo o CONTEÚDO quando devidamente notificado de que tal CONTEÚDO infringe o direito de propriedade intelectual de qualquer outra pessoa. O site SEBOOK se reserva no direito de remover o CONTEÚDO sem prévio aviso.<br>
            Quaisquer avisos ou comunicações, que uma das partes tenha de fazer a outra parte, em relação a quaisquer direitos ou obrigações contidas no presente instrumento, deverão adotar a forma escrita e serão tidas como eficazmente entregues no endereço constante do preâmbulo deste termo, se:<br>
            <b>A.</b> Entregues em mãos mediante protocolo escrito por quem de direito possa representar a parte remetida;<br>
            <b>B.</b> Enviadas por serviço de "courier" mediante protocolo escrito ou se pelo correio, na forma de carta registrada ("AR");<br>
            <b>C.</b> Enviadas por e-mail, ou outro meio eletrônico hábil para tais comunicações.<br>
            As partes convencionam o recebimento de mensagens e arquivos eletrônicos como prova documental para todos os efeitos, desde que com aviso de confirmação de recebimento ou outro tipo de protocolo que certifique o recebimento da comunicação.<br>
            Fica eleito o foro da Comarca de São Paulo, Estado de São Paulo, como competente para dirimir quaisquer controvérsias decorrentes deste TERMO DE USO independentemente de qualquer outro, por mais privilegiado que seja ou venha a ser.<br>
            O Sebook apoia todas as causas contra a divulgação de materiais ilegais, agressivos, caluniosos, abusivos, difamatórios, discriminatórios, ameaçadores, danosos, invasivos da privacidade de terceiros, terroristas, vulgares, obscenos ou ainda condenáveis de qualquer tipo ou natureza que sejam prejudiciais a menores e à preservação do meio ambiente de algum modo.<br>
            
            </p>
        </div>
    </section>
</article>